### ISSUE TITLE
Add ability to add assets to releases

### ISSUE THREAD

**Issue by Kamilcuk** [MeilCli/bump-release-action#1437]
Hi,

Please add the ability to add files as assets to the release.

## Feature description

I think it would be amazing, I could first build the app, and then specify "add this file as asset to the next release" bam, done.

This action is the best on github, you are amazing for making it, it is great, thank you.

**Comment by Kamilcuk** [comment]
Och, there is release json in the output and I can use https://github.com/actions/upload-release-asset ! I will try, this is great.

**Comment by Kamilcuk** [comment]
Like a charm, although getting the "fromJSON" was suprising:

```

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MeilCli/bump-release-action@v2
        id: create_release
        with:
          config_path: '.github/bump.yml'
          bump: ${{ github.event.inputs.bump }}
          dry_run: ${{ github.event.inputs.dry_run }}
          draft: ${{ github.event.inputs.draft }}
          pre_release: ${{ github.event.inputs.pre_release }}
          commit_user: ${{ github.actor }}
          commit_email: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ fromJSON(steps.create_release.outputs.release).upload_url }}
          asset_path: version.sh
          asset_name: version.sh
          asset_content_type: text/plain
```

It says that https://github.com/actions/upload-release-asset is deprecated, but still works with a warning.

Thank you!
