### ISSUE TITLE
Release notes reporting no changes.

### ISSUE THREAD

**Issue by Chris-Softrams** [MeilCli/bump-release-action#173]
## Description
Created a pull request with 1 commit:
```fix: Removed extra file```

After merging the pull request and having this action run. A new release is created, but lists no changes.
![image](https://user-images.githubusercontent.com/69363247/105403499-d1826c00-5bf6-11eb-880a-f2c9d728f9df.png)

If I compare the new release with the previous release I see
![image](https://user-images.githubusercontent.com/69363247/105403141-58831480-5bf6-11eb-9d7a-2fa83752bedb.png)

## Environment

bump-main.yaml
```
release:
  title-prefix: 't0.12-v'
  title-postfix: ' Released!'
  body-title: 'Changed'
  body-when-empty-changes: 'No changes'
  initial-version: '0.0.1'
  tag-prefix: 't0.12-v'
  commit-note-replacers:
    - replace-prefix: 'breaking: '
      new-prefix: 'Breaking'
    - replace-prefix: 'feature: '
      new-prefix: 'Feature '
    - replace-prefix: 'change: '
      new-prefix: 'Change '
    - replace-prefix: 'fix: '
      new-prefix: 'Fix '
    - replace-prefix: 'document: '
      new-prefix: 'Document '
    - replace-prefix: 'dependency: '
      new-prefix: 'Dependency '
branch:
  base-branch: 'main'
  version-branch-prefix: 'v'
  version-branch-postfix: ''
  create-major-version-branch: false
  create-minor-version-branch: false
  bump-version-commit-prefix: 'v'
  bump-version-commit-postfix: ''
categories:
  - title: 'Breaking Changes!'
    labels:
      - 'BreakingChange'
    commits:
      - 'breaking:'
    changes-prefix: ':warning: '
  - title: 'Changes'
    labels:
      - 'Feature'
    commits:
      - 'feature:'
    changes-prefix: ':gift: '
  - title: 'Changes'
    labels:
      - Maintenance
    commits:
      - 'change:'
    changes-prefix: ':hammer: '
  - title: 'Bug Fixes'
    labels:
      - 'Bug'
    commits:
      - 'fix:'
    changes-prefix: ':ambulance: '
  - title: 'Changes'
    labels:
      - 'Documentation'
    commits:
      - 'document:'
    changes-prefix: ':blue_book: '
  - title: 'Dependency Updates'
    labels:
      - 'Dependencies'
    skip-label: 'Development'
    commits:
      - 'dependency:'
    changes-prefix: ':green_book: '
bump:
  default: 'patch'
  major:
    labels:
      - 'BreakingChange'
    commits:
      - 'breaking:'
  minor:
    labels:
      - 'Feature'
    commits:
      - 'feature:'
```

release-main.yml
```
name: Release

on:
  push:
    branches:
      - main
    inputs:
      bump:
        description: 'bump type, major or minor or patch or empty string'
        default: ''
      dry_run:
        description: 'dry run, true or false'
        default: 'false'
      draft:
        description: 'draft, true or false'
        default: 'false'
      pre_release:
        description: 'pre release, true or false'
        default: 'false'
  workflow_dispatch:
    inputs:
      bump:
        description: 'bump type, major or minor or patch or empty string'
        default: ''
      dry_run:
        description: 'dry run, true or false'
        default: 'false'
      draft:
        description: 'draft, true or false'
        default: 'false'
      pre_release:
        description: 'pre release, true or false'
        default: 'false'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: MeilCli/bump-release-action@v1.0.7
        with:
          config_path: '.github/bump-main.yml'
          bump: ${{ github.event.inputs.bump }}
          dry_run: ${{ github.event.inputs.dry_run }}
          draft: ${{ github.event.inputs.draft }}
          pre_release: ${{ github.event.inputs.pre_release }}
```
