### ISSUE TITLE
No current branch name on Pull Request

### ISSUE THREAD

**Issue by DavoBR** [MeilCli/bump-release-action#295]
## Description

after create a pull request the action run and the result is the fowlling error, with push events it working

![image](https://user-images.githubusercontent.com/498724/122664044-d24f0800-d16c-11eb-8012-3d3a6b5c58ad.png)

## Environment

workflow.yml

```yaml
name: CI
on:
  push:
    branches:
      - master 

  pull_request:
    branches: 
      - master
  
  workflow_dispatch:
    inputs:
      bump:
        description: 'bump type, major or minor or patch or empty string'
        default: ''
        required: false
      dry_run:
        description: 'dry run, true or false'
        default: 'true'
        required: false
      draft:
        description: 'draft, true or false'
        default: 'true'
        required: false
      pre_release:
        description: 'pre release, true or false'
        default: 'false'
        required: false
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init Vars
        id: vars
        shell: bash
        run: |
          sourceBranch="${{ github.head_ref || github.ref }}" 
          sourceBranch="${sourceBranch/refs\/heads\//''}"

          echo "::set-output name=source_branch::$sourceBranch"

      - name: Bump config 
        if: steps.vars.outputs.source_branch != 'master'
        shell: bash
        env:
          BRANCH_NAME: ${{ steps.vars.outputs.source_branch }}
        run: |
          branchName=${BRANCH_NAME/\//'\/\/'}
          sed -i "s/base-branch: master/base-branch: $branchName/g" ./.github/bump.yml

      - name: Bump version 
        uses: MeilCli/bump-release-action@v1
        id: bump
        with:
          config_path: '.github/bump.yml'
          bump: ${{ github.event.inputs.bump || '' }}
          dry_run: ${{ github.event.inputs.dry_run || github.event_name == 'pull_request' }}
          draft: ${{ github.event.inputs.draft || 'true' }}
          pre_release: ${{ github.event.inputs.pre_release || 'false' }}
```

bump.yml

``` yaml
release:
  title-prefix: 'v'
  initial-version: '0.0.1'
  tag-prefix: 'v'
  commit-note-replacers:
    - replace-prefix: 'breaking: '
      new-prefix: ''
    - replace-prefix: 'feature: '
      new-prefix: ''
    - replace-prefix: 'feat: '
      new-prefix: ''
    - replace-prefix: 'change: '
      new-prefix: ''
    - replace-prefix: 'fix: '
      new-prefix: ''
    - replace-prefix: 'document: '
      new-prefix: ''
    - replace-prefix: 'dependency: '
      new-prefix: ''
branch:
  base-branch: master
  create-major-version-branch: false
categories:
  - title: 'Breaking Changes!'
    labels:
      - 'breaking-change'
    commits:
      - 'breaking:'
    changes-prefix: ':warning: '
  - title: 'Changes'
    labels:
      - 'feature'
      - 'enhancement'
    commits:
      - 'feature:'
    changes-prefix: ':gift: '
  - title: 'Changes'
    labels:
      - maintenance
    commits:
      - 'change:'
    changes-prefix: ':hammer: '
  - title: 'Bug Fixes'
    labels:
      - 'bug'
    commits:
      - 'fix:'
    changes-prefix: ':ambulance: '
  - title: 'Changes'
    labels:
      - 'documentation'
    commits:
      - 'document:'
    changes-prefix: ':blue_book: '
  - title: 'Dependency Updates'
    labels:
      - 'dependencies'
    skip-label: 'Development'
    commits:
      - 'dependency:'
    changes-prefix: ':green_book: '
bump:
  default: 'patch'
  major:
    labels:
      - 'breaking-change'
    commits:
      - 'breaking:'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
    commits:
      - 'feature:'
      - 'feat:'
```
