### ISSUE TITLE
"resource":"Release","code":"already_exists","field":"tag_name"

### ISSUE THREAD

**Issue by dstoyanoff** [MeilCli/bump-release-action#729]
Hello,
I've got an issue running the action. My setup looks like this:
I have a dev branch to which all PRs are targeted. Upon push to dev, I want to push a tag and create a pre-release. 

I was able to make it work with the first version. It created a tag v1.0.0 and a release v1.0.0
![image](https://user-images.githubusercontent.com/5079334/199029627-4689b809-11e4-4e26-a935-756f44790dd4.png)

On the next commit, it again listed all commits in the repo as if it was a first run and then printed `Error: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
`

Tested with dry-run and here is the output
![image](https://user-images.githubusercontent.com/5079334/199030446-b3f5565f-25aa-412e-9d0e-51ce01320eb3.png)

Here is my configuration:
Github Workflow:
```
      - uses: MeilCli/bump-release-action@v1.5.15
        id: release
        with:
          config_path: bump.yml
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          commit_user: spodio-bot
          commit_email: github-actions@github.com
          pre_release: true
          dry_run: true
```

bump.yml
```
release:
  title-prefix: v
  initialVersion: 1.0.0
  tag-prefix: v
  pull-request-commit: exclude
  commit-note-replacers:
    - replace-prefix: "[feature] "
      new-prefix: ""
    - replace-prefix: "[bug] "
      new-prefix: ""
    - replace-prefix: "[chore] "
      new-prefix: ""

branch:
  base-branch: dev
  create-major-version-branch: false

categories:
  - title: Features
    commits: ["[feature]"]
  - title: Fixes
    commits: ["[bug]"]
  - title: Chores
    commits: ["[chore]"]

bump:
  default: minor
  minor:
    commits: ["[feature]"]
  patch:
    commits: ["[bug]", "[chore]"]

```
