### ISSUE TITLE
bug: release branch not tracked by remote

### ISSUE THREAD

**Issue by grindlemire** [MeilCli/bump-release-action#785]
## Description

Hey! I was using this library and I think I ran into a bug where git complained that the local release branch checked out could not be merged with the existing remote release branch. The end result was that the very first release would work (because git would create a new v0 release branch) but every release after the first would not work because the action would try to create a local v0 branch that was not tracked by the remote v0 branch.

I fixed this issue locally and will put up a PR for your approval

## Error
```
/usr/bin/git branch
* main
/usr/bin/git checkout -b v0
Switched to a new branch 'v0'                             <-------------------- this is not a remote tracked branch
/usr/bin/git fetch -p
From https://github.com/grindlemire/my-repo
 * [new branch]      v0         -> origin/v0
 * [new tag]         v0.0.1     -> v0.0.1
/usr/bin/git merge --no-edit main
Already up to date.
/usr/bin/git push ***github.com/grindlemire/my-repo.git HEAD:v0
To https://github.com/grindlemire/my-repo.git
 ! [rejected]        HEAD -> v0 (non-fast-forward)
error: failed to push some refs to 'https://github.com/grindlemire/my-repo.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: The process '/usr/bin/git' failed with exit code 1
```

# action config
```
name: Bump Release

on:
    push:
        branches:
            - 'main'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: setup go
              uses: actions/setup-go@v3
              with:
                  go-version: 'stable'

            - name: test
              run: go test -v ./...

            - uses: MeilCli/bump-release-action@master
              with:
                  config_path: '.github/bump.yml'
```

## Environment
