### ISSUE TITLE
Generating release notes: yaml config

### ISSUE THREAD

**Issue by chaddyc** [MeilCli/bump-release-action#806]
I am using this github action as part of one of my project workflows however after configuring the `bump.yml` config according to the documentation steps but it still does not generate my release notes when I am bumping/creating a version?

**Comment by MeilCli** [comment]
Please show me your repository or workflow.
I don't know problem by your information.

**Comment by chaddyc** [comment]
```
# .github/bump.yml
release:
  title-prefix: "v"
  initial-version: "0.0.1"
  tag-prefix: "v"
  commit-note-replacers:
    - replace-prefix: "feat: "
      new-prefix: ""
    - replace-prefix: "fix: "
      new-prefix: ""
branch:
  base-branch: 'main'
  create-major-version-branch: false
  create-minor-version-branch: false
categories:
  - title: 'New Features'
    labels:
      - 'Feature'
    commits:
      - 'feat: '
    changes-prefix: ':gift: '
  - title: 'Bug Fixes'
    labels:
      - 'Fixes'
    commits:
      - 'fix: '
    changes-prefix: ':warning: '
bump:
  default: 'patch'
  major:
    labels:
      - 'Feature'
      - 'Fixes'
    commits:
      - 'feat: '
      - 'fix: '
  minor:
    labels:
      - 'Feature'
    commits:
      - 'feat: '
  patch:
    labels:
      - 'Fixes'
    commits:
      - 'fix: '
```
